feature:ui conversion into react
krishnaagarwal1506/HostelHubReact pull request #1
Opened 2023-10-21 08:14 UTC by krishnaagarwal1506

2023-10-21 08:22 UTC, shelly19gkmit commented on src/components/Navbar.jsx
> +    <>
no need to add extra empty tags if not needed, as nav tag is already present

2023-10-21 08:22 UTC, shelly19gkmit commented on src/layout/Dashboard.jsx
> +    <>
Same as above comment

2023-10-21 08:22 UTC, shelly19gkmit commented on src/pages/home/Facilities.jsx
> +};
maintain 1 line breaks after each functions

2023-10-21 08:22 UTC, shelly19gkmit commented on src/pages/home/Testimonials.jsx
> +};
same as above comment

2023-10-21 08:24 UTC, shelly19gkmit commented on src/pages/home/index.jsx
> +              />
Use loop approach for this kind of repetitive code

2023-10-21 08:24 UTC, shelly19gkmit commented on src/pages/home/index.jsx
> +      </section>   */}
remove unnecessary comments in all the files

2023-10-21 08:25 UTC, shelly19gkmit commented on src/pages/home/index.jsx
> +          <div>
So my much repetitive code, refactor this

2023-10-21 08:26 UTC, shelly19gkmit commented on src/pages/login/index.jsx
> +                <p className="error">This Field Is Required</p>
Why not use a reusable input field component?

2023-10-21 08:26 UTC, shelly19gkmit commented on src/pages/profile/index.jsx
> +              <span className="input-errors" id="studentPhone-error"></span>
same as above comment

2023-10-21 08:26 UTC, shelly19gkmit commented on src/pages/studyRoomSlots/index.jsx
> +          </select>
Refactoring needed here

2023-10-23 09:04 UTC, shelly19gkmit commented on assets/desk-workspace-with-various-elements.jpg
Files shouldn't be greater or around Mbs

2023-10-23 09:04 UTC, shelly19gkmit commented on src/components/Navbar.jsx
> +    <>
is this resolved? Can't see updated changes

2023-10-23 09:05 UTC, shelly19gkmit commented on src/pages/login/index.jsx
> +                />
Integrate reusable components

2023-10-23 09:35 UTC, shelly19gkmit commented on src/components/AlertToast.jsx
> +        zIndex: "3",
maintain colors in a separate constant file

2023-10-23 09:36 UTC, shelly19gkmit commented on src/pages/profile/index.jsx
>                <span className="input-errors" id="email-error"></span>
Integrate resuable component

2023-10-23 09:37 UTC, krishnaagarwal1506 commented
changes done.
Working on the profile and studySlotRoom pages

2023-10-23 10:21 UTC, krishnaagarwal1506 commented on assets/desk-workspace-with-various-elements.jpg
ok.

2023-10-24 06:42 UTC, Delwalt requested changes

2023-10-24 06:42 UTC, Delwalt commented on .eslintrc.cjs
> +module.exports = {
How come eslint is part of this PR, were you asked to add eslint? As far as I remember it will come in the milestone 4

2023-10-24 06:42 UTC, Delwalt commented on .gitignore
> +yarn-debug.log*
why all these fils were added here?

yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*


I can see lots of files here which are not even being used.

2023-10-24 06:42 UTC, Delwalt commented on README.md
> +# React + Vite
why readme is not updated?

2023-10-24 06:42 UTC, Delwalt commented on index.html
> +    <title>Vite + React</title>
title is not updated

2023-10-24 06:42 UTC, Delwalt commented on src/components/AlertToast.jsx
> +      style={{
Ideally we should avoid adding inline styles. For conditional styling you can add classes conditionally.

Suggestion 

```
<div
      className={`popup ${messageType === "positive" ? "success-popup" : "error-popup"}`
```

2023-10-24 06:42 UTC, Delwalt commented on src/components/AlertToast.jsx
> +import { AlertContext } from "@context/AlertContext";
why `AlertContext` variable is in PascalCase ? Is it a class or component ?

2023-10-24 06:42 UTC, Delwalt commented on src/components/AlertToast.jsx
> +  if (!popup.isVisible) {
above you have already destructured the `isVisible` you can do this
```suggestion
  if (!isVisible) {
```

2023-10-24 12:55 UTC, closed without merging